import { expect } from '@playwright/test';
import { test } from '../assets/jest-helper.js';

/**
 * Wallet-at-rest format tests (v1 salted KDF + legacy migration).
 *
 * The fixture blobs and expected KDF outputs below were generated by an
 * independent reference implementation (python stdlib hashlib/hmac + openssl
 * CLI for AES-256-CBC), so these tests pin the WebCrypto callbacks and the
 * shared C++ wallet format against an implementation that shares no code
 * with beekeeper.
 *
 * Fixture wallet: password "fixture-pass", single imported key
 * 5JkFnXrLM2ap9t3AmAxBJvQHF7xSKtnTrCTginQCkhzU5S7ecPT
 * (STM5RqVBAVNp5ufMCetQtvLGLJo7unX9nyCBMMrTXRWQ9i1Zzzizh).
 */

const FIXTURE_PASSWORD = 'fixture-pass';
const FIXTURE_PUBLIC_KEY = 'STM5RqVBAVNp5ufMCetQtvLGLJo7unX9nyCBMMrTXRWQ9i1Zzzizh';

// Pre-v1 scheme: AES-256-CBC keyed by one unsalted SHA-512 of the password.
const LEGACY_WALLET_HEX =
  '23279e80bad106e06b60ee11322d79f92e2dd72eed60bcba837b05f90e50128ef0cf23d2ed81afcbee559a5c2acccd06' +
  '43e5a21d60ba61c7b2f6ed78a29e98403085382f536bf197c60af92641e71662eaf531e166ce07ba3fb1143d3bed942e' +
  'daaced3e1e6b30e5d5f33521b67cc58874cb617f6d9c7dd56caad67a10ef8940c500d816facf721cb8e610dd986d277e';

// v1 scheme: "BEEKWLT" | ver 1 | kdf 1 | 4096 iters | salt | iv | ciphertext | HMAC-SHA256 tag.
const V1_WALLET_HEX =
  '4245454b574c5401010010000010000102030405060708090a0b0c0d0e0f10101112131415161718191a1b1c1d1e1f' +
  '67edcb46992feedbfab1e8849069a75d14e89bca7c154384de797b7b49c51e078100080657f8b5dbe2052911dae498' +
  'db1845bb40f9d9dc4ce80a21756258fc716f2dc2566863028f82b442b43d73301fca2753d806abc28fbb1cad32c167' +
  'ebc467b0696442b2ca669ac534bc17311856';

// Same key, legacy scheme, EMPTY password (historically creatable) — pins the
// empty-password PBKDF2 path through migration.
const LEGACY_EMPTY_PASSWORD_WALLET_HEX =
  'e55c18891d4f3ce7ebcd7f71dbb80b575eec1df164abf5bf47ea8e02b0316052bab1161b6f90bca0361c4e592da902' +
  '02964c602b74282bb594a63f24f219dcc613159b35213b5931161f3a44790bdae92f7c3f0d69a3609f01e3afb9556e' +
  '5bd096352bf2d78ab75aa43e200f3b5b8a9511a8b6e766a6623ba82c913ea67c7ba027e978dc61f5716cf68e0d68ca' +
  'd3a844';

// Hex of "BEEKWLT" + version byte 0x01.
const V1_MAGIC_HEX = '4245454b574c5401';

// 600000 (the production default iteration count) as u32 LE hex, at header
// offset 9 = hex chars [18, 26).
const DEFAULT_ITERATIONS_HEX = 'c0270900';

test.describe('Wallet-at-rest format', () => {
  test('PBKDF2-HMAC-SHA512 and HMAC-SHA256 callbacks match reference vectors', async ({ beekeeperWasmTest }) => {
    const result = await beekeeperWasmTest(async ({ cryptoCallbacks }) => {
      const toHex = (bytes: Uint8Array | null) =>
        bytes === null ? null : Array.from(bytes).map(byte => byte.toString(16).padStart(2, '0')).join('');
      const encoder = new TextEncoder();

      const dk1 = await cryptoCallbacks.pbkdf2HmacSha512(encoder.encode('password'), encoder.encode('salt'), 1, 64);
      const dk2 = await cryptoCallbacks.pbkdf2HmacSha512(
        encoder.encode('passwordPASSWORDpassword'), encoder.encode('saltSALTsaltSALTsaltSALTsaltSALTsalt'), 4096, 64);
      const mac = await cryptoCallbacks.hmacSha256(encoder.encode('Jefe'), encoder.encode('what do ya want for nothing?'));

      return { dk1: toHex(dk1), dk2: toHex(dk2), mac: toHex(mac) };
    });

    expect(result.dk1).toBe(
      '867f70cf1ade02cff3752599a3a53dc4af34c7a669815ae5d513554e1c8cf252' +
      'c02d470a285a0501bad999bfe943c08f050235d7d68b1da55e63f73b60a57fce');
    expect(result.dk2).toBe(
      '8c0511f4c6e597c6ac6315d8f0362e225f3c501495ba23b868c005174dc4ee71' +
      '115b59f9e60cd9532fa33e0f75aefe30225c583a186cd82bd4daea9724a3d3b8');
    expect(result.mac).toBe('5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843');
  });

  test('Newly created wallets are stored in the salted v1 format with the default work factor', async ({ beekeeperWasmTest }) => {
    const result = await beekeeperWasmTest(async ({ provider, cryptoCallbacks }, magicHex) => {
      const store = new Map<string, Uint8Array>();
      const storage = {
        save_fn: (name: string, data: Uint8Array) => { store.set(name, new Uint8Array(data)); },
        load_fn: (name: string) => { const data = store.get(name); if (!data) throw new Error('Wallet not found: ' + name); return data; },
        list_dir_fn: () => Array.from(store.keys())
      };
      // No kdf_iterations constructor argument — this pins the production default.
      const api = new provider.beekeeper_api(storage, cryptoCallbacks, 900);
      const token = await api.create_session('salt');
      await api.create(token, 'w0', 'format-pass', false);

      const storedHex = new TextDecoder().decode(store.get('w0')).replace(/"/g, '');
      api.delete();
      return { isV1: storedHex.startsWith(magicHex), iterationsHex: storedHex.slice(18, 26) };
    }, V1_MAGIC_HEX);

    expect(result.isV1).toBe(true);
    expect(result.iterationsHex).toBe(DEFAULT_ITERATIONS_HEX);
  });

  test('Legacy and independently generated v1 wallets unlock; legacy migrates on unlock', async ({ beekeeperWasmTest }) => {
    const result = await beekeeperWasmTest(async ({ provider, cryptoCallbacks }, legacyHex, v1Hex, password, magicHex) => {
      const encoder = new TextEncoder();
      const store = new Map<string, Uint8Array>();
      // Wallet files are JSON hex strings — plant both fixtures as stored files.
      store.set('legacy', encoder.encode('"' + legacyHex + '"'));
      store.set('external_v1', encoder.encode('"' + v1Hex + '"'));
      const storage = {
        save_fn: (name: string, data: Uint8Array) => { store.set(name, new Uint8Array(data)); },
        load_fn: (name: string) => { const data = store.get(name); if (!data) throw new Error('Wallet not found: ' + name); return data; },
        list_dir_fn: () => Array.from(store.keys())
      };
      const api = new provider.beekeeper_api(storage, cryptoCallbacks, 900);
      const token = await api.create_session('salt');

      await api.open(token, 'legacy');
      await api.unlock(token, 'legacy', password);
      const legacyKeys = Array.from(await api.get_public_keys(token, 'legacy'));

      // A successful unlock transparently re-encrypts the legacy file as v1.
      const migratedIsV1 = new TextDecoder().decode(store.get('legacy')).replace(/"/g, '').startsWith(magicHex);

      // The migrated blob itself unlocks (lock, then decrypt the v1 rewrite).
      await api.lock(token, 'legacy');
      await api.unlock(token, 'legacy', password);
      const remigratedKeys = Array.from(await api.get_public_keys(token, 'legacy'));

      // A v1 wallet produced by the independent reference implementation unlocks too.
      await api.open(token, 'external_v1');
      await api.unlock(token, 'external_v1', password);
      const v1Keys = Array.from(await api.get_public_keys(token, 'external_v1'));

      await api.lock(token, 'external_v1');
      let wrongPasswordRejected = false;
      try {
        await api.unlock(token, 'external_v1', 'not-the-password');
      } catch {
        wrongPasswordRejected = true;
      }

      api.delete();
      return { legacyKeys, v1Keys, migratedIsV1, remigratedKeys, wrongPasswordRejected };
    }, LEGACY_WALLET_HEX, V1_WALLET_HEX, FIXTURE_PASSWORD, V1_MAGIC_HEX);

    expect(result.legacyKeys).toEqual([FIXTURE_PUBLIC_KEY]);
    expect(result.v1Keys).toEqual([FIXTURE_PUBLIC_KEY]);
    expect(result.migratedIsV1).toBe(true);
    expect(result.remigratedKeys).toEqual([FIXTURE_PUBLIC_KEY]);
    expect(result.wrongPasswordRejected).toBe(true);
  });

  test('Legacy wallet with an empty password unlocks, migrates and re-unlocks', async ({ beekeeperWasmTest }) => {
    const result = await beekeeperWasmTest(async ({ provider, cryptoCallbacks }, legacyEmptyHex, magicHex) => {
      const encoder = new TextEncoder();
      const store = new Map<string, Uint8Array>();
      store.set('legacy_empty', encoder.encode('"' + legacyEmptyHex + '"'));
      const storage = {
        save_fn: (name: string, data: Uint8Array) => { store.set(name, new Uint8Array(data)); },
        load_fn: (name: string) => { const data = store.get(name); if (!data) throw new Error('Wallet not found: ' + name); return data; },
        list_dir_fn: () => Array.from(store.keys())
      };
      const api = new provider.beekeeper_api(storage, cryptoCallbacks, 900);
      const token = await api.create_session('salt');

      await api.open(token, 'legacy_empty');
      await api.unlock(token, 'legacy_empty', '');
      const keys = Array.from(await api.get_public_keys(token, 'legacy_empty'));
      const migratedIsV1 = new TextDecoder().decode(store.get('legacy_empty')).replace(/"/g, '').startsWith(magicHex);

      // The migrated v1 wallet decrypts with the empty password again — this
      // exercises the empty-password PBKDF2 path in the WebCrypto callback.
      await api.lock(token, 'legacy_empty');
      await api.unlock(token, 'legacy_empty', '');
      const keysAfter = Array.from(await api.get_public_keys(token, 'legacy_empty'));

      api.delete();
      return { keys, migratedIsV1, keysAfter };
    }, LEGACY_EMPTY_PASSWORD_WALLET_HEX, V1_MAGIC_HEX);

    expect(result.keys).toEqual([FIXTURE_PUBLIC_KEY]);
    expect(result.migratedIsV1).toBe(true);
    expect(result.keysAfter).toEqual([FIXTURE_PUBLIC_KEY]);
  });

  test('A failing KDF callback surfaces as a catchable error, not a WASM abort', async ({ beekeeperWasmTest }) => {
    const result = await beekeeperWasmTest(async ({ provider, cryptoCallbacks }) => {
      const makeStorage = () => {
        const store = new Map<string, Uint8Array>();
        return {
          save_fn: (name: string, data: Uint8Array) => { store.set(name, new Uint8Array(data)); },
          load_fn: (name: string) => { const data = store.get(name); if (!data) throw new Error('Wallet not found: ' + name); return data; },
          list_dir_fn: () => Array.from(store.keys())
        };
      };

      // Callbacks whose KDF reports failure via null (the never-reject contract).
      const brokenCallbacks = { ...cryptoCallbacks, pbkdf2HmacSha512: async () => null };
      const brokenApi = new provider.beekeeper_api(makeStorage(), brokenCallbacks, 900);
      const brokenToken = await brokenApi.create_session('salt');
      let createFailedCleanly = false;
      try {
        await brokenApi.create(brokenToken, 'w0', 'pass', false);
      } catch {
        createFailedCleanly = true;
      }
      brokenApi.delete();

      // The module must still be fully functional afterwards.
      const api = new provider.beekeeper_api(makeStorage(), cryptoCallbacks, 900);
      const token = await api.create_session('salt');
      await api.create(token, 'w1', 'pass', false);
      const stillWorks = await api.has_wallet(token, 'w1');
      api.delete();

      return { createFailedCleanly, stillWorks };
    });

    expect(result.createFailedCleanly).toBe(true);
    expect(result.stillWorks).toBe(true);
  });
});
